version: "3.9"
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bioregex
    depends_on:
      - db
  web:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  celery:
    build: ./backend
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
volumes:
  db_data:
